services:
  events-service:
    build:
      context: ../srumec-events-service
      dockerfile: Dockerfile
      target: prod
    command: npm run start
    env_file:
      - ../srumec-events-service/.env.prod
    ports:
      - "4000:4000"