services:
  rabbitmq-service:
    build: ../srumec-rabbitmq-service
    env_file:
      - ../srumec-rabbitmq-service/.env.dev

  events-service:
    build:
      context: ../srumec-events-service
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    volumes:
      - ../srumec-events-service:/app
      - /app/node_modules
    env_file:
      - ../srumec-events-service/.env.dev
      - ../srumec-rabbitmq-service/.env.dev
    ports:
      - "4000:4000"

  events-postgres:
    image: postgis/postgis:16-3.4
    env_file:
      - ../srumec-events-service/.env.dev

  chats-service:
    build:
      context: ../srumec-chats-service
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    volumes:
      - ../srumec-chats-service:/app
      - /app/node_modules
    env_file:
      - ../srumec-chats-service/.env.dev
      - ../srumec-rabbitmq-service/.env.dev
    ports:
      - "4001:4000"

  chats-postgres:
    image: postgis/postgis:16-3.4
    env_file:
      - ../srumec-chats-service/.env.dev

  expire-service:
    build:
      context: ../srumec-expire-service
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    volumes:
      - ../srumec-expire-service:/app
      - /app/node_modules
    env_file:
      - ../srumec-expire-service/.env.dev
      - ../srumec-rabbitmq-service/.env.dev

  ws-service:
    container_name: ws-service
    build:
      context: ../srumec-ws-service
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    volumes:
      - ../srumec-ws-service:/app
      - /app/node_modules
    env_file:
      - ../srumec-ws-service/.env.dev
      - ../srumec-rabbitmq-service/.env.dev
    ports:
      - '4004:4001'

  users-service:
    ports:
      - '4002:8080'

  admin-api:
    ports:
      - "4003:8080"

  events-seeder:
    build:
      context: ../srumec-events-service
      dockerfile: Dockerfile
      target: dev
    command: ["npm", "run", "db:init"]
    env_file:
      - ../srumec-events-service/.env.dev

  chats-seeder:
    build:
      context: ../srumec-chats-service
      dockerfile: Dockerfile
      target: dev
    command: ["npm", "run", "db:init"]
    env_file:
      - ../srumec-chats-service/.env.dev