services:
  rabbitmq-service:
    build: ../srumec-rabbitmq-service
    env_file:
      - ../srumec-rabbitmq-service/.env.prod
    networks:
      - shrumec-net

  events-service:
    build:
      context: ../srumec-events-service
      dockerfile: Dockerfile
      target: prod
    command: npm run start
    env_file:
      - ../srumec-events-service/.env.prod
      - ../srumec-rabbitmq-service/.env.prod
    networks:
      - shrumec-net

  events-postgres:
    image: postgis/postgis:16-3.4
    env_file:
      - ../srumec-events-service/.env.prod
    networks:
      - shrumec-net

  events-seeder:
    build:
      context: ../srumec-events-service
      dockerfile: Dockerfile
      target: prod
    command: ["npm", "run", "db:init"]
    env_file:
      - ../srumec-events-service/.env.prod
    networks:
      - shrumec-net

  chats-service:
    build:
      context: ../srumec-chats-service
      dockerfile: Dockerfile
      target: prod
    command: npm run start
    env_file:
      - ../srumec-chats-service/.env.prod
      - ../srumec-rabbitmq-service/.env.prod
    networks:
      - shrumec-net

  chats-postgres:
    image: postgis/postgis:16-3.4
    env_file:
      - ../srumec-chats-service/.env.prod
    networks:
      - shrumec-net

  chats-seeder:
    build:
      context: ../srumec-chats-service
      dockerfile: Dockerfile
      target: prod
    command: ["npm", "run", "db:init"]
    env_file:
      - ../srumec-chats-service/.env.prod
    networks:
      - shrumec-net

  expire-service:
    build:
      context: ../srumec-expire-service
      dockerfile: Dockerfile
      target: prod
    command: npm run start
    env_file:
      - ../srumec-expire-service/.env.prod
      - ../srumec-rabbitmq-service/.env.prod
    networks:
      - shrumec-net

  ws-service:
    container_name: ws-service
    build:
      context: ../srumec-ws-service
      dockerfile: Dockerfile
      target: prod
    command: npm run start
    env_file:
      - ../srumec-ws-service/.env.prod
      - ../srumec-rabbitmq-service/.env.prod
    networks:
      - shrumec-net

  pgadmin:
    networks:
      - shrumec-net

  auth-service:
    networks:
      - shrumec-net

  auth-postgres:
    networks:
      - shrumec-net

  auth-gateway:
    networks:
      - shrumec-net

  expire-redis:
    networks:
      - shrumec-net

  users-service:
    networks:
      - shrumec-net

  users-postgres:
    networks:
      - shrumec-net

  admin-api:
    networks:
      - shrumec-net

networks:
  shrumec-net:
    driver: bridge
